// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzokqkzpkfvbjgsrserz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6b2txa3pwa2Z2Ympnc3JzZXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzUzODcsImV4cCI6MjA3MzgxMTM4N30.7wge6J3SqeFszB2f4IDZtxiyjBs6LunVItpxPRPzuz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});